version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - db
      
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"