version: "2"
services:
  app:
    container_name: app
    image: trustlab/ixo-pds
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - db
      
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  cli:
    container_name: cli
    image: trustlab/pds-cli
    stdin_open: true
    tty: true